# Quarkus
quarkus.http.port=8082
production.workflow.manager.environment=development
quarkus.vertx.warning-exception-time=5000

# Rest
quarkus.rest-client.feature-flag-service-api.url=${feature.flag.service.url}
feature.flag.service.url=http://localhost:8080
quarkus.rest-client.network-cache-api.url=${network.cache.url}
network.cache.url=http://localhost:8081

# Database
quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:h2:file:./database/production_workflow_simulator_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;FILE_LOCK=SOCKET
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.db-version=2.2.0
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

# Kafka
kafka.bootstrap.servers=localhost:9093
mp.messaging.incoming.development-flags-in.connector=smallrye-kafka
mp.messaging.incoming.development-flags-in.topic=development-flags
mp.messaging.incoming.development-flags-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.stage-flags-in.connector=smallrye-kafka
mp.messaging.incoming.stage-flags-in.topic=stage-flags
mp.messaging.incoming.stage-flags-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.production-flags-in.connector=smallrye-kafka
mp.messaging.incoming.production-flags-in.topic=production-flags
mp.messaging.incoming.production-flags-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Machine Simulation Speed
machine.simulation.speed.assembly.cron.expr=1/5 * * * * ?
machine.simulation.speed.quality.cron.expr=3/5 * * * * ?
machine.simulation.speed.packaging.cron.expr=5/5 * * * * ?
