services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ffms-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - ffms-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ffms-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - ffms-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: ffms-kafdrop
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
      - SERVER_SERVLET_CONTEXT_PATH=/kafdrop
    ports:
      - "9000:9000"
    networks:
      - ffms-network
    depends_on:
      - kafka
    links:
      - kafka

  mysql:
    image: mysql:latest
    container_name: ffms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feature_flag_db
      MYSQL_USER: ffms
      MYSQL_PASSWORD: F3atureFl4g
    ports:
      - "3306:3306"
    networks:
      - ffms-network
    volumes:
      - mysql_data:/var/lib/mysql

  ffms-quarkus:
    container_name: ffms-quarkus-app
    build:
      context: .
      dockerfile: Dockerfile.jvm
    depends_on:
      - mysql
      - kafka
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/feature_flag_db
      QUARKUS_DATASOURCE_USERNAME: ffms
      QUARKUS_DATASOURCE_PASSWORD: F3atureFl4g
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"
    networks:
      - ffms-network

volumes:
  mysql_data:

networks:
  ffms-network:
    driver: bridge
