%QUARKUS
quarkus.http.port=8080

%DATABASE
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=ffms
quarkus.datasource.password=F3atureFl4g
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/feature_flag_db
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

%KAFKA
kafka.bootstrap.servers=localhost:9093
mp.messaging.outgoing.development-flags-out.connector=smallrye-kafka
mp.messaging.outgoing.development-flags-out.topic=development-flags
mp.messaging.outgoing.development-flags-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.stage-flags-out.connector=smallrye-kafka
mp.messaging.outgoing.stage-flags-out.topic=stage-flags
mp.messaging.outgoing.stage-flags-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.production-flags-out.connector=smallrye-kafka
mp.messaging.outgoing.production-flags-out.topic=production-flags
mp.messaging.outgoing.production-flags-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
